/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-XSLT.h
 #	source generated by 4D Plugin Wizard
 #	Project : XSLT
 #	author : miyako
 #	2019/09/17
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_XSLT_H
#define PLUGIN_XSLT_H

#include "4DPluginAPI.h"

#include <libxml/xmlmemory.h>
#include <libxml/debugXML.h>
#include <libxml/HTMLtree.h>
#include <libxml/xmlIO.h>
#include <libxml/parser.h>
#include <libxml/xinclude.h>
#include <libxml/catalog.h>

#include <libxslt/xslt.h>
#include <libxslt/xsltInternals.h>
#include <libxslt/transform.h>
#include <libxslt/xsltutils.h>
#include <libxslt/security.h>
#include <libexslt/exslt.h>

#include "json/json.h"

#include "C_BLOB.h"

#include "4DPlugin-JSON.h"

#pragma mark -

void XSLT_Apply_stylesheet(PA_PluginParameters params);

#endif /* PLUGIN_XSLT_H */
